manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: Liam-Weitzel
      url-base: https://github.com/Liam-Weitzel
  projects:
    - name: zmk
      remote: Liam-Weitzel
      revision: main
      import: app/west.yml
  self:
    path: config
